/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * ati_mach64: which registers the model consumes -- the bitmap
 * behind the `silent-regs` diagnostic property.
 *
 * Generated by doc/radeon9800/regaudit2.py mach64-g3 --emit-table
 * over the ati_mach64 sources. Bit (offset>>2) set => some model code
 * consumes the register: a named constant for the offset is
 * referenced outside ati_mach64_regs.h/ati_mach64_dbg.c, the offset lies
 * in a bank the code walks from its base constant, or it falls
 * inside a `case A ... B:` range. Regenerate whenever the model
 * learns to read a new register, or silent-regs will keep
 * reporting it.
 */
#ifndef ATI_MACH64_AUDIT_H
#define ATI_MACH64_AUDIT_H

#define MACH64_REG_AUDIT_LIMIT 0x1000
static const uint32_t ati_mach64_reg_consumed[32] = {
    0x5f0000e5, 0x01110010, 0x00081f7f, 0xf98123ff, 0x000fffff, 0xdc773f07,
    0x00105017, 0x000d0000, 0x0004a773, 0x00000000, 0x00000000, 0x0000c007,
    0x77f70000, 0x00000077, 0x00000003, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000,
};

#endif
